[package]
name = "veriventure_contracts"
version = "0.1.0"
authors = ["VeriVenture <founders@veriventure.ai>"]
edition = "2021"

[dependencies]
ink = { workspace = true, default-features = false, features = ["unstable-hostfn"] }
scale = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
primitive-types = { workspace = true }
sp-core = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true, optional = true }
dotenvy = { workspace = true, optional = true }
achievement_badge = { path = "../contracts/achievement_badge", default-features = false }

[dev-dependencies]
ink_e2e = "6.0.0-alpha"

[lib]
path = "lib.rs"

[[bin]]
name = "instantiate_contracts"
path = "bin/instantiate.rs"
required-features = ["std"]

[[bin]]
name = "extract_address"
path = "bin/extract_address.rs"
required-features = ["std"]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "primitive-types/std",
    "sp-core/std",
    "achievement_badge/std",
    "anyhow",
    "dotenvy",
]
ink-as-dependency = []
