[workspace]
members = [
    "contracts/achievement_badge",
    "workspace",
]
default-members = ["workspace"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["VeriVenture <founders@veriventure.ai>"]
version = "0.1.0"

[workspace.dependencies]
ink = { version = "6.0.0-alpha", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"] }
sp-core = { version = "33.0.0", default-features = false, features = ["std"] }
hex = "0.4"
anyhow = { version = "1.0", default-features = true }
dotenvy = { version = "0.15" }
primitive-types = { version = "0.13", default-features = false, features = ["codec"] }
